### PR TITLE
Unbreak Ceph again

### PR DESCRIPTION
**Pull request by dirkmueller**
We do want to set a mon attribute not an osd attribute.

### CODE REVIEW

**Comment by vuntz** [comment]
+1

**Comment by jsuchome** [comment]
+1

**Comment by tboerger** [comment]
:+1:

**Comment by mjura** [comment]
+1 
Should we wait for gating tests?

**Comment by dirkmueller** [comment]
@mjura since the previous change(s) were merged without testing, I'd wait to see that I found all regressions introduced in the last change.

**Pull request merged**
