### PR TITLE
Workaround Ceph hanging QEMU on volume attach (bsc#967509)

### PR DESCRIPTION
**Pull request by dirkmueller**

### CODE REVIEW

**Comment by toabctl** [comment]
+1 (also tested it, works).

**Comment by vuntz** [comment]
So that doesn't help us for external ceph clusters. I'm wondering if it's worth working around it here in that case.

**Comment by dirkmueller** [comment]
Yeah, but given the frequency and the impact of the bug I'd consider a workaround necessary until maintenance update is released - that also fixes the external ceph case.

**Comment by vuntz** [comment]
Hrm, okay. As long as we track that this needs to be reverted...

**Pull request merged**
