### PR TITLE
Backport fixes for bsc#948522 and bsc#972001 to SOC6

### PR DESCRIPTION
**Pull request by tserong**
This is a backport of PRs #47 and #49.

### CODE REVIEW

**Comment by tserong** [comment]
(#47 isn't merged yet, so this should wait until that happens in case anyone flags anything)

**Comment by tserong** [comment]
@vuntz, @mjura, @dirkmueller, care to review? :-)

**Comment by vuntz** [comment]
+1

**Comment by mjura** [comment]
+1

**Pull request merged**
