### PR TITLE
Allow deployment on SLES 12 SP2

### PR DESCRIPTION
**Pull request by tserong**
Signed-off-by: Tim Serong tserong@suse.com

### CODE REVIEW

**Comment by nicolasbock** [comment]
+1 (gating failure is again the NFS mount problem and not related)

**Comment by vuntz** [comment]
+1

**Comment by vuntz** [comment]
Although note that for OpenStack, we use `"suse" => "< 12.2"` as exclusion. Don't know if you want to adopt the same model here...

**Comment by tserong** [comment]
Doesn't `"< 12.2"` mean only SP1? Or am I misreading that?

**Comment by tserong** [comment]
Can we get this merged?

**Comment by Itxaka** [comment]
gating triggered

**Comment by tserong** [comment]
Gating failure is some ceilometer problem?

**Comment by vuntz** [comment]
> Doesn't "< 12.2" mean only SP1? Or am I misreading that?

Sorry, didn't see your comment. I was talking about exclude_platform, not about platform. So it means SP2 or later.

**Comment by tserong** [comment]
Ah, OK, understood. I'm still happy to leave this as-is if everyone else is happy though :)

**Comment by vuntz** [comment]
Gating fails when trying to install the ceph package. I somehow suspect we're at a stage where some of the product expects SP1 for ceph and other parts expects SP2, with the setup being possibly done by mkcloud only for SES 3 or SES 4... But just guessing, didn't investigate.

**Comment by toabctl** [comment]
Hm. How can I retrigger gating when the job is no longer available?

**Comment by vuntz** [comment]
> Hm. How can I retrigger gating when the job is no longer available?

You can just re-create the cloud-crowbar-testbuild-pr job from scratch, as the arguments are pretty easy to fill. I just did it: https://ci.suse.de/view/Cloud/view/Builds/job/cloud-crowbar-testbuild-pr/6839/ -- it will then re-trigger mkcloud.

**Review by dirkmueller — APPROVED** [review]

**Comment by toabctl** [comment]
CI failed with:

```
11:45:46 [2016-10-18T09:45:43+00:00] INFO: Processing package[calamari-clients] action install (ceph::calamari line 13)
11:45:46 
11:45:46 ================================================================================
11:45:46 Error executing action `install` on resource 'package[calamari-clients]'
11:45:46 ================================================================================
11:45:46 
11:45:46 Mixlib::ShellOut::ShellCommandFailed
11:45:46 ------------------------------------
11:45:46 Expected process to exit with [0], but received '104'
11:45:46 ---- Begin output of zypper-retry --non-interactive install --auto-agree-with-licenses calamari-clients ----
11:45:46 STDOUT: Loading repository data...
11:45:46 Reading installed packages...
11:45:46 'calamari-clients' not found in package names. Trying capabilities.
11:45:46 STDERR: No provider of 'calamari-clients' found.
11:45:46 ---- End output of zypper-retry --non-interactive install --auto-agree-with-licenses calamari-clients ----
11:45:46 Ran zypper-retry --non-interactive install --auto-agree-with-licenses calamari-clients returned 104
11:45:46 
11:45:46 Resource Declaration:
11:45:46 ---------------------
11:45:46 # In /var/chef/cache/cookbooks/ceph/recipes/calamari.rb
11:45:46 
11:45:46  13:   package pkg
11:45:46  14: end
11:45:46 
11:45:46 Compiled Resource:
11:45:46 ------------------
11:45:46 # Declared in /var/chef/cache/cookbooks/ceph/recipes/calamari.rb:13:in `block in from_file'
11:45:46 
11:45:46 package("calamari-clients") do
11:45:46   action :install
11:45:46   retries 0
11:45:46   retry_delay 2
11:45:46   package_name "calamari-clients"
11:45:46   cookbook_name "ceph"
11:45:46   recipe_name "calamari"
11:45:46 end
11:45:46 
```

but I guess it's unrelated.

**Review by toabctl — APPROVED** [review]

**Pull request merged**
