### PR TITLE
Deploy a single MDS node by default

### PR DESCRIPTION
**Pull request by toabctl**
When deploying Ceph, also deploy a single MDS node on the controller.

### CODE REVIEW

**Comment by toabctl** [comment]
@tserong or is there any reason to not deploy mds by default? It helps at least for testing but we can also deploy mds in mkcloud...

**Comment by tserong** [comment]
@toabctl none that I can think of, LGTM.

**Comment by toabctl** [comment]
@tserong to be able to merge this, I need 2 github reviews.

**Review by mjura — COMMENTED** [review]
Code looks correct, but I would like to get information from @tserong about minimal requirements for ceph-mds service

**Comment by mjura** [comment]
On official website project there are minimum requirements specified http://docs.ceph.com/docs/jewel/start/hardware-recommendations/

```
Processor   
1x 64-bit AMD-64 quad-core
1x 32-bit ARM quad-core
1x i386 quad-core
RAM 1 GB minimum per daemon
Disk Space 1 MB per daemon
Network 2x 1GB Ethernet NICs
```

**Review by tserong — APPROVED** [review]
LGTM

**Review by mjura — APPROVED** [review]
+1

**Pull request merged**
