### PR TITLE
[3.0] Update incorrect caps instead recreating whole client key, (bsc#961108)

### PR DESCRIPTION
**Pull request by mjura**
Backport of https://github.com/crowbar/crowbar-ceph/pull/32

### CODE REVIEW

**Comment by vuntz** [comment]
+1

**Comment by vuntz** [comment]
@mjura maybe cherry-pick https://github.com/crowbar/crowbar-ceph/pull/43 for the last commit?

**Comment by mjura** [comment]
@vuntz : done cherry-picked with -x

**Comment by vuntz** [comment]
+1

**Comment by dirkmueller** [comment]
+1

**Pull request merged**
